// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBej8ts8mhU5gjbOgEwjtQrXxtpAoy9J9A',
    appId: '1:265372483289:web:7ea4bf9fe0984b39cd08c8',
    messagingSenderId: '265372483289',
    projectId: 'lyrica-feafd',
    authDomain: 'lyrica-feafd.firebaseapp.com',
    storageBucket: 'lyrica-feafd.appspot.com',
    measurementId: 'G-03G35GMWJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYwbRFD1lzK06RfeDM6xKAR_HTlfCq6w',
    appId: '1:265372483289:android:245568677b0244cfcd08c8',
    messagingSenderId: '265372483289',
    projectId: 'lyrica-feafd',
    storageBucket: 'lyrica-feafd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMgL5ejG_Na0S-1FUcXP2NQFaZ7hbYTI',
    appId: '1:265372483289:ios:cfec33b0e53fcc87cd08c8',
    messagingSenderId: '265372483289',
    projectId: 'lyrica-feafd',
    storageBucket: 'lyrica-feafd.appspot.com',
    iosBundleId: 'com.example.lyrica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUMgL5ejG_Na0S-1FUcXP2NQFaZ7hbYTI',
    appId: '1:265372483289:ios:cfec33b0e53fcc87cd08c8',
    messagingSenderId: '265372483289',
    projectId: 'lyrica-feafd',
    storageBucket: 'lyrica-feafd.appspot.com',
    iosBundleId: 'com.example.lyrica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBej8ts8mhU5gjbOgEwjtQrXxtpAoy9J9A',
    appId: '1:265372483289:web:dbfd4b76c497b590cd08c8',
    messagingSenderId: '265372483289',
    projectId: 'lyrica-feafd',
    authDomain: 'lyrica-feafd.firebaseapp.com',
    storageBucket: 'lyrica-feafd.appspot.com',
    measurementId: 'G-BNJ1S1LYSJ',
  );
}
